name: Bug Report
description: Report a bug or issue with AstroTimes
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Your feedback helps make AstroTimes better for everyone.

        **Note**: This project is maintained by the repository owner. While external pull requests are not currently being accepted, bug reports are highly valued and will be reviewed.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is.
      placeholder: Tell us what went wrong...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run command '...'
        2. Enter input '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened.
      placeholder: Instead, what happened was...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: AstroTimes Version
      description: What version of AstroTimes are you using?
      placeholder: "e.g., 0.1.0, built from source on 2025-10-23"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - macOS
        - Linux
        - Windows
        - Other
    validations:
      required: true

  - type: input
    id: rust-version
    attributes:
      label: Rust Version (if building from source)
      description: Output of `rustc --version`
      placeholder: "e.g., rustc 1.70.0"

  - type: textarea
    id: logs
    attributes:
      label: Error Messages / Logs
      description: Any error messages or relevant output.
      render: shell
      placeholder: Paste error messages here...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem.
      placeholder: Add any other context or screenshots here...
